name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: rabits/qt:5.11-desktop
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        env 
        g++ -v
        cd qml-states
        sudo /opt/Qt/5.11.3/gcc_64/bin/qmake qml-states.pro
        sudo make -j2
        ls -l
    - uses: actions/upload-artifact@v1
      with:
       name: my-artifact
       path: qml-states
        
        
